# fly.toml app configuration file for spot-poller
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'staktrakr-spot'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[env]
  API_DATA_REPO = "https://github.com/lbruton/StakTrakrApi.git"
  API_EXPORT_DIR = "/tmp/staktrakr-api-export"
  DATA_DIR = "/tmp/staktrakr-api-export/data"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
